server:
  port: 8088
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto:  update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root






